DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS DIRECTOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS MOVIE_GENRE;

CREATE TABLE DIRECTOR (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
  -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MOVIE (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  imdb_score FLOAT NOT NULL DEFAULT 0.0,
  popularity FLOAT NOT NULL DEFAULT 0.0,
  director_id INTEGER,
  -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (director_id) REFERENCES DIRECTOR (id)
);

CREATE TABLE GENRE (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
  -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MOVIE_GENRE (
  movie_id INTEGER,
  genre_id INTEGER,
  FOREIGN KEY (movie_id) REFERENCES MOVIE (id),
  FOREIGN KEY (genre_id) REFERENCES GENRE (id)
  -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
